// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7REcZREaz91n9zsrWoNT4erhbgyAnPxI',
    appId: '1:676523624401:web:b3a2a5dd36323c56c142f0',
    messagingSenderId: '676523624401',
    projectId: 'fruit-hub-d0a9f',
    authDomain: 'fruit-hub-d0a9f.firebaseapp.com',
    storageBucket: 'fruit-hub-d0a9f.firebasestorage.app',
    measurementId: 'G-7JLXT748M3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-rzIhKTlijr4ToKaXsHlDpBwV2cyjHo0',
    appId: '1:676523624401:android:d573e1b6f599e1abc142f0',
    messagingSenderId: '676523624401',
    projectId: 'fruit-hub-d0a9f',
    storageBucket: 'fruit-hub-d0a9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC094gGtVc_b-3zvoNVR745x8BPdJC_Xb4',
    appId: '1:676523624401:ios:7acda79ad6caccf3c142f0',
    messagingSenderId: '676523624401',
    projectId: 'fruit-hub-d0a9f',
    storageBucket: 'fruit-hub-d0a9f.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC094gGtVc_b-3zvoNVR745x8BPdJC_Xb4',
    appId: '1:676523624401:ios:7acda79ad6caccf3c142f0',
    messagingSenderId: '676523624401',
    projectId: 'fruit-hub-d0a9f',
    storageBucket: 'fruit-hub-d0a9f.firebasestorage.app',
    iosBundleId: 'com.example.fruitsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7REcZREaz91n9zsrWoNT4erhbgyAnPxI',
    appId: '1:676523624401:web:2592e2a79cbe1586c142f0',
    messagingSenderId: '676523624401',
    projectId: 'fruit-hub-d0a9f',
    authDomain: 'fruit-hub-d0a9f.firebaseapp.com',
    storageBucket: 'fruit-hub-d0a9f.firebasestorage.app',
    measurementId: 'G-NGNL1HQB17',
  );
}
